DELETE http://localhost:3003/api/blogs/6230e73a77a5e4fc3eceb4a9
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNjIyYjJkODk4Yjk1ODVhODRiNDJmNGMwIiwiaWF0IjoxNjQ3ODcxNDQ3fQ.Q80uflE5Q0r09zFYUW6sh-kuL-jqZSe5IfYftpIlabI